version: '3.7'

services:
  clickhouse-server:
    image: yandex/clickhouse-server
    container_name: clickhouse-server
    environment:
      - CLICKHOUSE_USER=ura
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 
    ports:
      - "8123:8123"
      - "9000:9000"



